### ISSUE TITLE
Hi can we use this indian market by taking data from yfinance for every 2 min, why the development is stopped

### ISSUE THREAD

**Issue by raviyellani** [SnowCheetos/Emsemble-Tradebot#5]

**Comment by SnowCheetos** [comment]
Sure, as long as the API provides the necessary fields of data. As of now the exchange API calls are made in `src/wallet.py` so if you want to contribute you can make adjustments there.

I have been quite busy recently and also distraction from other projects caused me to not pay too much attention to this one. I do have a lot of optimization and refactoring in mind though, I will certainly do more devs for this project in the upcoming weeks.
